version: '2'
services:
    angularwar-app:
        image: angularwar
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://angularwar-mysql:3306/angularwar?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    angularwar-mysql:
        extends:
            file: mysql.yml
            service: angularwar-mysql
